image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest

.ewaol-hardknott:
  stage: build
  tags:
    - yocto
  variables:
    GIT_STRATEGY: none
    POKY_REV: 269265c00091fa65f93de6cad32bf24f1e7f72a3
    OPENEMBEDDED_REV: f44e1a2b575826e88b8cb2725e54a7c5d29cf94a
    SECURITY_REV: 16c68aae0fdfc20c7ce5cf4da0a9fff8bdd75769
    VIRTUALIZATION_REV: 7f719ef40896b6c78893add8485fda995b00d51d
    EWAOL_REV: 116cfb967ed6f97db2096c1de4d9f552ea2d8fbd
    CONF_DIR: meta-renesas/docs/template/conf/${PLATFORM}/ewaol
    DL_DIR: ${CI_PROJECT_DIR}/downloads
    SSTATE_DIR: ${CI_PROJECT_DIR}/sstate_cache
  before_script:
    - export
    - rm -rf build && sync
    - mkdir build && cd build
  script:
    - git clone https://git.yoctoproject.org/git/poky
    - cd poky && git checkout ${POKY_REV} && cd -
    - git clone https://github.com/openembedded/meta-openembedded
    - cd meta-openembedded && git checkout ${OPENEMBEDDED_REV}  && cd -
    - git clone https://git.yoctoproject.org/meta-security
    - cd meta-security && git checkout ${SECURITY_REV} && cd -
    - git clone https://git.yoctoproject.org/meta-virtualization
    - cd meta-virtualization && git checkout ${VIRTUALIZATION_REV} && cd -
    - git clone https://git.gitlab.arm.com/ewaol/meta-ewaol.git
    - cd meta-ewaol && git checkout ${EWAOL_REV} && cd -
    - git clone git@gitlab.renesas.solutions:spl2/civil-infrastructure-platform/meta-renesas.git
    - cd meta-renesas && git checkout ${CI_COMMIT_REF_NAME} && cd -
    - source poky/oe-init-build-env
    - cp ${CI_PROJECT_DIR}/build/${CONF_DIR}/*.conf conf/
    - echo "DL_DIR=\"${DL_DIR}\"" >> conf/local.conf
    - echo "SSTATE_DIR=\"${SSTATE_DIR}\"" >> conf/local.conf
    - if [[ "${IMAGE}" == *"-sdk" ]]; then echo "DISTRO_FEATURES_append=\" ewaol-sdk\"" >> conf/local.conf; fi
    - bitbake ${IMAGE}
  cache:
    - key: "downloads"
      paths:
        - ${DL_DIR}
    - key: "sstate-cache-${PLATFORM}-${IMAGE}"
      paths:
        - ${SSTATE_DIR}
  artifacts:
    expire_in: 1 week
    paths:
      - build/build/tmp/deploy/images/

smarc-rzg2l_core-image-minimal:
  extends: .ewaol-hardknott
  variables:
    PLATFORM: smarc-rzg2l
    IMAGE: core-image-minimal
  when: manual

smarc-rzg2l_ewaol-image-docker:
  extends: .ewaol-hardknott
  variables:
    PLATFORM: smarc-rzg2l
    IMAGE: ewaol-image-docker

smarc-rzg2l_ewaol-image-docker-sdk:
  extends: .ewaol-hardknott
  variables:
    PLATFORM: smarc-rzg2l
    IMAGE: ewaol-image-docker-sdk
  when: manual

smarc-rzg2l_ewaol-image-podman:
  extends: .ewaol-hardknott
  variables:
    PLATFORM: smarc-rzg2l
    IMAGE: ewaol-image-podman

smarc-rzg2l_ewaol-image-podman-sdk:
  extends: .ewaol-hardknott
  variables:
    PLATFORM: smarc-rzg2l
    IMAGE: ewaol-image-podman-sdk
  when: manual
